name: build-sphinx-docs

on: workflow_dispatch
        
jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v2
            
            - name: Set up Python 3.10
              uses: actions/setup-python@v2
              with:
                pyhton-version: "3.10"
                
            - name: Run a one-line script
              run: echo Hellow, world!
              
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                
            - name: Build HTML
              run: |
                cd docs/
                make html
                
            - name: Run ghp-import
              run: |
                ghp-import -n -p -f docs/build/html