name: build-sphinx-docs

on:
    push:
        branches: [master]
        
jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v2
            
            - name: Set up Python 3.10
              uses: actions/setup-python@v2
              with:
                pyhton-version: "3.10"
                
            - name: Run a one-line script
              run: echo Hellow, world!